monitoror/monitoror

Makefile, scripts/build/build
Ticket: https://github.com/monitoror/monitoror/issues/39
=> Rename darwin into macos

go.mod, go.sum, monitorable/config/usecase/config.go, monitorable/config/usecase/verify.go, monitorable/config/usecase/verify_test.go, test/faker-config.json
=> feat(config): add columnSpan and rowSpan in config

front/src/components/SubTile.vue, front/src/components/Tile.vue
only check previousStatus when isQueued or isRunning
=> fix(front): display right background status color

front/package.json, front/src/store.ts, front/yarn.lock
Update group state on each subtile update to be more reactive-like.
=> Fix groups late state

front/src/App.vue
=> Hide cursor after non move while 10s

front/src/App.vue, front/src/components/SubTile.vue, front/src/components/Tile.vue, front/src/store.ts
Add `&theme=dark` to the URL to switch to the dark theme
=> Dark theme

monitorable/http/usecase/http.go, monitorable/http/usecase/http_test.go, service/server_api.go
Avoid downloading same file when url is the same
ex: same url, different json key
fix: #89
=> perf(back/http): add cache for http request by url

monitorable/http/usecase/http.go, service/server_api.go
changing downstream to upstream
=> perf(back/http): fix wrong config key

middlewares/cache.go, middlewares/cache_test.go
avoid error if uri contains %...
=> refactor(back/cache): replace sprintf by replace

monitorable/config/usecase/hydrate.go, monitorable/config/usecase/hydrate_test.go, monitorable/config/usecase/verify.go, monitorable/config/usecase/verify_test.go
=> fix(back/config): remove empty group if hydrate return no tile

front/src/store.ts, monitorable/config/delivery/http/handlers.go, monitorable/config/mocks/Usecase.go, monitorable/config/usecase.go, monitorable/config/usecase/hydrate.go, monitorable/config/usecase/hydrate_test.go, service/server_api_faker.go
I remove host:port injection in hydrate step.
Next is only in front. Poke @Alex-D
=> Remove Host:Port in hydrated configuration

.github/workflows/continuous-integration.yml
see: https://github.com/reviewdog/action-golangci-lint/issues/21
=> chore(build/lint): move linter into anthor job

models/tile.go, monitorable/azuredevops/usecase/azuredevops.go, monitorable/azuredevops/usecase/azuredevops_faker.go, monitorable/azuredevops/usecase/azuredevops_test.go, monitorable/jenkins/usecase/jenkins.go, monitorable/jenkins/usecase/jenkins_faker.go, monitorable/jenkins/usecase/jenkins_test.go, monitorable/travisci/usecase/travisci.go, monitorable/travisci/usecase/travisci_faker.go, monitorable/travisci/usecase/travisci_test.go, pkg/monitoror/utils/git/git.go, pkg/monitoror/utils/git/git_test.go
=> Refactor build tile label

.gitignore, ui/.gitignore
IDE ignore should be in user global `.gitignore` file
=> Clean gitignore files

docs/assets/demo.monitoror.com-config.json
=> fix(config/demo): fix remaining values

config/config.go, faker-configs/faker-build-config.json, monitorable/config/mocks/Helper.go, monitorable/config/mocks/Usecase.go, monitorable/config/models/config.go, monitorable/config/usecase.go, monitorable/config/usecase/getconfig_test.go, monitorable/config/usecase/hydrate.go, monitorable/config/usecase/hydrate_test.go, monitorable/config/usecase/usecase.go, service/server_api.go, service/server_api_faker.go, ui/src/App.vue, ui/src/classes/monitororTile.ts, ui/src/classes/task.ts, ui/src/components/SubTile.vue, ui/src/components/Tile.vue, ui/src/enums/taskInterval.ts, ui/src/enums/taskType.ts, ui/src/interfaces/taskOptions.ts, ui/src/interfaces/tileConfig.ts, ui/src/store.ts
=> Add delay on config

docs/assets/demo.monitoror.com-config.json, docs/documentation/index.html, docs/index.html, faker-configs/faker-build-config.json, faker-configs/faker-config.json, faker-configs/faker-zoom-config.json, monitorable/config/models/config.go, monitorable/config/usecase/usecase.go, monitorable/config/usecase/verify.go, monitorable/config/usecase/verify_test.go, ui/public/index.html, ui/src/App.vue, ui/src/components/Tile.vue, ui/src/interfaces/config.ts, ui/src/store.ts
=> Add zoom parameter and mobile support based on it

monitorable/http/usecase/http.go, monitorable/http/usecase/http_test.go
=> fix(core/http): ignore body with HTTP-STATUS

.github/workflows/continuous-integration.yml, scripts/.variables
- Fix release binaries versions
- Change date format to YYYYMMDDHHMMSS in dev binaries version
=> Fix binaries version

.github/workflows/continuous-integration.yml
CI no longer create the release
=> chore(build): improve release process

monitorable/config/usecase/hydrate.go, monitorable/config/usecase/hydrate_test.go, monitorable/config/usecase/usecase_test.go, monitorable/http/usecase/http.go, pkg/monitoror/utils/humanize/humanize.go, pkg/monitoror/utils/humanize/humanize_test.go
=> Fix pingdom check

monitorables/azuredevops/api/repository/api.go, monitorables/azuredevops/api/repository/api_test.go
=> feat(core/azuredevops): inject refs/heads/ if the branch doesn't start with

api/config/usecase/hydrate.go, api/config/usecase/hydrate_test.go
=> feat(core/config): forward dynamic tile label to generated tiles

api/config/usecase/hydrate.go, api/config/usecase/hydrate_test.go, docs/documentation/index.html, monitorables/azuredevops/api/repository/api.go, monitorables/azuredevops/api/repository/api_test.go, monitorables/github/api/repository/api.go, monitorables/github/api/repository/api_test.go, monitorables/github/config/config.go, monitorables/github/github.go, monitorables/github/github_test.go, monitorables/jenkins/api/repository/api.go, monitorables/jenkins/api/repository/api_test.go, monitorables/pingdom/api/repository/api.go, monitorables/pingdom/api/repository/api_test.go, monitorables/pingdom/pingdom_test.go, monitorables/travisci/api/repository/api.go, monitorables/travisci/api/repository/api_test.go
=> Feat GitHub on premise support

docs/documentation/index.html
=> Add notes about JSON-escaping regex to documentation

ui/src/components/SubTile.vue, ui/src/components/Tile.vue
=> Break long words in labels

ui/src/store.ts, ui/vue.config.js
=> Make UI working even when served with route prefix

api/config/usecase/getconfig.go, api/config/usecase/getconfig_test.go
=> Lowercase config name

docs/index.html
=> Use PORT instead of PING in landing example

scripts/setup-variables.sh
=> Fix missing CGO_ENABLED flag
